name: developer bob
url: http://zbo.github.io
description: A blog recording code and more...

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
